name: build-trips-api

on:
  push:
    paths:
      - 'apis/trips/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'apis/trips/*'
jobs:

  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: apis/trip
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Get dependencies
      run: go get

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -v ./tripsgo -run Unit
