name: Docker Image CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: apis/trips

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        login-server: openhackmix2x3l6acr.azurecr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest
    
  # - name: Build the Docker image
  #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
