name: Docker Image CI

on:
  push:
    branches: [ emaema1-patch-2 ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: apis/trips

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: openhackmix2x3l6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: apis/trips
        push: true
        tags: devopsoh/api-trips:${{ github.run_id }}
    
