name: Docker Build and Push Trips API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apis/trips/**'
      - '.github/workflows/push-trips-api.yml'


jobs:
  docker-build-deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: apis/trips

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Azure Registry
      uses: docker/login-action@v1 
      with:
        registry: openhackmix2x3l6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: apis/trips
        push: true
        tags: openhackmix2x3l6acr.azurecr.io/devopsoh/api-trips:1.${{ github.run_number }}
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - uses: azure/webapps-deploy@v2
      with:
        slot-name: 'staging' 
        app-name: 'openhackmix2x3l6trips'
        images: 'openhackmix2x3l6acr.azurecr.io/devopsoh/api-trips:1.${{ github.run_number }}'

    - name: Implement health check
      run: |
          ./scripts/poll.ps1
      shell: pwsh
      timeout-minutes: 1
    
    - name: Azure logout
      run: |
        az logout

    
