# This is a basic workflow to help you get started with Actions

name: raise_issue_on_failure

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["build-trips-api"]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:

